apiVersion: v1
kind: Pod
metadata:
  labels:
    run: alpha
  name: alpha
spec:
  containers:
  - image: nicolaka/netshoot
    command:
    - ping
    - google.com
    name: netshoot
  - image: nginx
    name: web
  restartPolicy: Never

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    run: beta
  name: beta
spec:
  containers:
  - image: nicolaka/netshoot
    command:
    - ping
    - google.com
    name: netshoot
  - image: tomcat
    name: jee
  restartPolicy: Never
